### ISSUE TITLE
System Unavailable

### ISSUE THREAD

**Issue by jagos01** [poeli/GOTTCHA2#2]
Hello,
I am trying to download the taxonomy dmp species signature index files (https://edge-lanl.gov/rest_of_path).  I am redirected to https://lanal.gov/errors/system-notification.php with the following message displayed:
System Unavailable
We are currently performing system maintenance.
I have been receiving this message for about a month now.  Is there another download location for these files?  This also affects downloading databases/tools for the EDGE and PanGIA as they are in the same root path.
Thanks,
 Scott

**Comment by poeli-lanl** [comment]
Hey Scott,

I’m sorry that our servers are still recovering from a major power outage last month. I will try to find a temporary location to host the files.

Thanks,
Paul

On Feb 27, 2020, at 8:08 AM, jagos01 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I am trying to download the taxonomy dmp species signature index files (https://edge-lanl.gov/rest_of_path). I am redirected to https://lanal.gov/errors/system-notification.php with the following message displayed:
System Unavailable
We are currently performing system maintenance.
I have been receiving this message for about a month now. Is there another download location for these files? This also affects downloading databases/tools for the EDGE and PanGIA as they are in the same root path.
Thanks,
Scott

**Comment by jagos01** [comment]
Hello Paul,
Sorry to hear that.  I am sure you have more pressing work.  I can wait
until the servers are back on line.
Thanks
Scott
